import 'dart:convert';

class User {
  User(
      {this.id,
      this.service_id,
      this.user_id,
      this.firstname,
      this.image,
      this.videos,
      this.description,
      this.location,
      this.price,
      this.start_date,
      this.end_date,
      this.latitute,
      this.longitute,
      this.age,
      this.sport,
      this.gender,
      this.is_certified,
      this.distance,
      this.lastname,
      this.type,
      this.date,
      this.tag_name,
      this.tag_image,
      this.service_type_name,
      this.service_type_color,
      this.rating,
      this.favorite,
      this.isAd});

  String id,
      service_id,
      user_id,
      firstname,
      image,
      videos,
      description,
      location,
      price,
      start_date,
      end_date,
      latitute,
      longitute,
      age,
      sport,
      gender,
      is_certified,
      distance,
      lastname,
      type,
      date,
      tag_name,
      tag_image,
      service_type_name,
      service_type_color,
      rating,
      favorite,
      isAd;

  factory User.fromJson(Map value) {
    List tags = value['tags'];
    return User(
        id: value['id'],
        service_id: value['service_id'],
        user_id: value['user_id'],
        firstname: value['firstname'],
        image: value['image'],
        videos: value['videos'],
        description: value['description'],
        location: value['location'],
        price: value['price'],
        start_date: value['start_date'],
        end_date: value['end_date'],
        latitute: value['latitute'],
        longitute: value['longitute'],
        age: value['age'],
        sport: value['sport'],
        gender: value['gender'],
        is_certified: value['is_certified'],
        distance: value['distance'],
        lastname: value['lastname'],
        type: value['type'],
        date: value['date'],
        tag_name: tags.length == 0 ? '' : tags[0]['name'],
        tag_image: tags.length == 0 ? '' : tags[0]['image'],
        service_type_name: value['service_type_name'],
        service_type_color: value['service_type_color'],
        rating: value['rating'],
        favorite: value['favorite'],
        isAd: value['isAd']);
  }
}
